// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PsiArtigos.Infrastructure.Persistence;

#nullable disable

namespace PsiArtigos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PsiArtigosDbContext))]
    partial class PsiArtigosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Abstract")
                        .HasColumnType("text");

                    b.Property<int>("CitationCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PrimarySource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StudyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.ArticleContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("ArticleContents", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.GeneratedInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ArticleId", "Type");

                    b.ToTable("GeneratedInsights", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.LearningTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LearningTrails", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.ReadingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveReadingSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastOpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpenCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique();

                    b.ToTable("ReadingSessions", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("FreshnessScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SourceArticleId")
                        .HasColumnType("uuid");

                    b.Property<double>("TopicScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDismissed");

                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("_resultArticleIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResultArticleIdsJson");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastAccessedAtUtc");

                    b.ToTable("SearchQueries", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.UserReaderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserReaderSettings", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Entities.CitationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ToArticleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromArticleId", "ToArticleId", "LinkType")
                        .IsUnique();

                    b.ToTable("CitationLinks", (string)null);
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Article", b =>
                {
                    b.OwnsMany("PsiArtigos.Domain.ValueObjects.TopicTag", "_topics", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("ArticleId");

                            b1.ToTable("ArticleTopics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsMany("PsiArtigos.Domain.ValueObjects.Author", "_authors", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Affiliation")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Orcid")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ArticleId");

                            b1.ToTable("ArticleAuthors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsMany("PsiArtigos.Domain.ValueObjects.ExternalReference", "_externalReferences", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("ArticleId");

                            b1.HasIndex("System", "ExternalId");

                            b1.ToTable("ArticleExternalReferences", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.OwnsOne("PsiArtigos.Domain.ValueObjects.PublicationInfo", "Publication", b1 =>
                        {
                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Doi")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Doi");

                            b1.Property<string>("Url")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Url");

                            b1.Property<string>("Venue")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Venue");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("Year");

                            b1.HasKey("ArticleId");

                            b1.HasIndex("Doi");

                            b1.ToTable("Articles");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("Publication")
                        .IsRequired();

                    b.Navigation("_authors");

                    b.Navigation("_externalReferences");

                    b.Navigation("_topics");
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.Collection", b =>
                {
                    b.OwnsMany("PsiArtigos.Domain.ValueObjects.CollectionItem", "_items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("AddedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ArticleId");

                            b1.HasIndex("CollectionId");

                            b1.ToTable("CollectionItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CollectionId");
                        });

                    b.Navigation("_items");
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.LearningTrail", b =>
                {
                    b.OwnsMany("PsiArtigos.Domain.Entities.TrailStep", "_steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Difficulty")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("LearningTrailId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Rationale")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("LearningTrailId");

                            b1.ToTable("LearningTrailSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LearningTrailId");
                        });

                    b.Navigation("_steps");
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.ReadingSession", b =>
                {
                    b.OwnsMany("PsiArtigos.Domain.Entities.Highlight", "_highlights", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("QuotedText")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ReadingSessionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReadingSessionId");

                            b1.ToTable("Highlights", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReadingSessionId");

                            b1.OwnsMany("PsiArtigos.Domain.Entities.Annotation", "_annotations", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAtUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("HighlightId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Note")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("UpdatedAtUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("Id");

                                    b2.HasIndex("HighlightId");

                                    b2.ToTable("Annotations", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("HighlightId");
                                });

                            b1.OwnsOne("PsiArtigos.Domain.ValueObjects.TextRange", "Range", b2 =>
                                {
                                    b2.Property<Guid>("HighlightId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("EndOffset")
                                        .HasColumnType("integer")
                                        .HasColumnName("EndOffset");

                                    b2.Property<int?>("PageNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("PageNumber");

                                    b2.Property<int>("StartOffset")
                                        .HasColumnType("integer")
                                        .HasColumnName("StartOffset");

                                    b2.HasKey("HighlightId");

                                    b2.ToTable("Highlights");

                                    b2.WithOwner()
                                        .HasForeignKey("HighlightId");
                                });

                            b1.Navigation("Range")
                                .IsRequired();

                            b1.Navigation("_annotations");
                        });

                    b.OwnsOne("PsiArtigos.Domain.ValueObjects.ReadingProgress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("ReadingSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CharacterOffset")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressCharacterOffset");

                            b1.Property<int?>("PageNumber")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressPageNumber");

                            b1.Property<double>("Percent")
                                .HasColumnType("double precision")
                                .HasColumnName("ProgressPercent");

                            b1.HasKey("ReadingSessionId");

                            b1.ToTable("ReadingSessions");

                            b1.WithOwner()
                                .HasForeignKey("ReadingSessionId");
                        });

                    b.Navigation("Progress")
                        .IsRequired();

                    b.Navigation("_highlights");
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.SearchQuery", b =>
                {
                    b.OwnsOne("PsiArtigos.Domain.ValueObjects.SearchFilters", "Filters", b1 =>
                        {
                            b1.Property<Guid>("SearchQueryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Language")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("FilterLanguage");

                            b1.Property<int?>("MinCitations")
                                .HasColumnType("integer")
                                .HasColumnName("FilterMinCitations");

                            b1.Property<string>("StudyType")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("FilterStudyType");

                            b1.Property<int?>("YearMax")
                                .HasColumnType("integer")
                                .HasColumnName("FilterYearMax");

                            b1.Property<int?>("YearMin")
                                .HasColumnType("integer")
                                .HasColumnName("FilterYearMin");

                            b1.Property<string>("_sources")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FilterSourcesJson");

                            b1.HasKey("SearchQueryId");

                            b1.ToTable("SearchQueries");

                            b1.WithOwner()
                                .HasForeignKey("SearchQueryId");
                        });

                    b.Navigation("Filters")
                        .IsRequired();
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.User", b =>
                {
                    b.OwnsOne("PsiArtigos.Domain.ValueObjects.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("DisplayName");

                            b1.Property<string>("PreferredLanguage")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("PreferredLanguage");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("PsiArtigos.Domain.ValueObjects.TopicTag", "_interests", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("UserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserId");

                                    b2.ToTable("UserInterests", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("UserId");
                                });

                            b1.Navigation("_interests");
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("PsiArtigos.Domain.Aggregates.UserReaderSettings", b =>
                {
                    b.OwnsOne("PsiArtigos.Domain.ValueObjects.ReaderPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserReaderSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("DarkMode")
                                .HasColumnType("boolean")
                                .HasColumnName("DarkMode");

                            b1.Property<int>("FontSize")
                                .HasColumnType("integer")
                                .HasColumnName("FontSize");

                            b1.Property<string>("PreferredTranslationLanguage")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("PreferredTranslationLanguage");

                            b1.HasKey("UserReaderSettingsId");

                            b1.ToTable("UserReaderSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserReaderSettingsId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
